const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs');
const os = require('os');
const path = require('path');
const {
  assembleAuthorPackage,
  checkAuthorPackageEntry,
  readAuthorPackage,
  writeAuthorPackageEntry,
} = require('../../src/authoring');

test('readAuthorPackage validates config and resolves ordered source files', () => {
  const root = makePackageFixture();
  const configPath = path.join(root, 'deck.config.json');

  const sourcePackage = readAuthorPackage(configPath);

  assert.equal(sourcePackage.rootDir, root);
  assert.equal(sourcePackage.entryPath, path.join(root, 'deck.html'));
  assert.deepEqual(sourcePackage.styleFiles.map((file) => file.relativePath), [
    'styles/tokens.css',
    'styles/layout.css',
  ]);
  assert.deepEqual(sourcePackage.pageFiles.map((file) => file.id), ['cover', 'agenda']);
});

test('assembleAuthorPackage creates a complete generated deck without mutating source fragments', () => {
  const root = makePackageFixture();
  const result = assembleAuthorPackage(path.join(root, 'deck.config.json'));

  assert.match(result.html, /Generated by html-indesign/);
  assert.match(result.html, /<style data-source-file="styles\/tokens\.css">/);
  assert.match(result.html, /<style data-source-file="styles\/layout\.css">/);
  assert.match(result.html, /<main class="deck" data-id-document="demo-deck"/);
  assert.match(result.html, /data-id-source-file="pages\/00-cover\.html"/);
  assert.match(result.html, /data-id-source-file="pages\/01-agenda\.html"/);
  assert.match(result.html, /<section class="page" data-page="cover"/);
  assert.match(result.html, /<section class="page" data-page="agenda"/);
});

test('assembleAuthorPackage writes source package metadata on main', () => {
  const root = makePackageFixture();
  const { html } = assembleAuthorPackage(path.join(root, 'deck.config.json'));

  assert.match(html, /<main class="deck"[^>]+data-id-source-package-config="deck\.config\.json"/);
  assert.match(html, /data-id-source-package-schema="1"/);
  assert.match(html, /<style data-source-file="styles\/tokens\.css">/);
  assert.match(html, /<section[^>]+data-id-source-file="pages\/00-cover\.html"/);
});

test('writeAuthorPackageEntry and checkAuthorPackageEntry detect generated entry drift', () => {
  const root = makePackageFixture();
  const configPath = path.join(root, 'deck.config.json');

  writeAuthorPackageEntry(configPath);
  assert.deepEqual(checkAuthorPackageEntry(configPath), {
    ok: true,
    entryPath: path.join(root, 'deck.html'),
  });

  fs.appendFileSync(path.join(root, 'deck.html'), '\n<!-- manual edit -->\n', 'utf8');
  const dirty = checkAuthorPackageEntry(configPath);
  assert.equal(dirty.ok, false);
  assert.equal(dirty.entryPath, path.join(root, 'deck.html'));
  assert.match(dirty.message, /generated deck\.html is out of date/i);
});

test('readAuthorPackage rejects missing page fragments with a clear error code', () => {
  const root = makePackageFixture();
  fs.rmSync(path.join(root, 'pages/01-agenda.html'));

  assert.throws(
    () => readAuthorPackage(path.join(root, 'deck.config.json')),
    /AUTHOR_PAGE_FILE_MISSING/
  );
});

function makePackageFixture() {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'hi-author-package-'));
  fs.mkdirSync(path.join(root, 'styles'), { recursive: true });
  fs.mkdirSync(path.join(root, 'pages'), { recursive: true });
  fs.writeFileSync(path.join(root, 'styles/tokens.css'), ':root { --ink: #123456; }\n', 'utf8');
  fs.writeFileSync(path.join(root, 'styles/layout.css'), '.page { width: 1600px; height: 900px; }\n', 'utf8');
  fs.writeFileSync(
    path.join(root, 'pages/00-cover.html'),
    '<section class="page" data-page="cover" id="cover-page"><h1 data-id-object>Cover</h1></section>\n',
    'utf8'
  );
  fs.writeFileSync(
    path.join(root, 'pages/01-agenda.html'),
    '<section class="page" data-page="agenda" id="agenda-page"><h2 data-id-object>Agenda</h2></section>\n',
    'utf8'
  );
  fs.writeFileSync(
    path.join(root, 'deck.config.json'),
    JSON.stringify({
      schemaVersion: 1,
      id: 'demo-deck',
      title: 'Demo Deck',
      profile: 'architecture-report',
      unitMode: 'presentation',
      targetSize: 'source',
      entry: 'deck.html',
      styles: ['styles/tokens.css', 'styles/layout.css'],
      pages: [
        { id: 'cover', file: 'pages/00-cover.html' },
        { id: 'agenda', file: 'pages/01-agenda.html' },
      ],
      assets: { root: 'assets' },
    }, null, 2),
    'utf8'
  );
  return root;
}
