const fs = require('fs');
const path = require('path');

const GENERATED_COMMENT = '<!-- Generated by html-indesign. Edit pages/*.html and styles/*.css, not this file. -->';

function readAuthorPackage(configPath) {
  if (!configPath) throw new Error('AUTHOR_PACKAGE_CONFIG_MISSING: config path is required');
  const resolvedConfigPath = path.resolve(configPath);
  if (!fs.existsSync(resolvedConfigPath)) {
    throw new Error(`AUTHOR_PACKAGE_CONFIG_MISSING: ${resolvedConfigPath}`);
  }

  const rootDir = path.dirname(resolvedConfigPath);
  const config = JSON.parse(fs.readFileSync(resolvedConfigPath, 'utf8'));
  if (config.schemaVersion !== 1) {
    throw new Error(`AUTHOR_PACKAGE_SCHEMA_UNSUPPORTED: ${config.schemaVersion}`);
  }
  if (!config.id || typeof config.id !== 'string') {
    throw new Error('AUTHOR_PACKAGE_ID_MISSING: deck.config.json must define id');
  }
  if (!config.entry || typeof config.entry !== 'string') {
    throw new Error('AUTHOR_PACKAGE_ENTRY_MISSING: deck.config.json must define entry');
  }

  const styleFiles = (config.styles || []).map((relativePath) => {
    const filePath = resolveInside(rootDir, relativePath, 'AUTHOR_STYLE_FILE_OUTSIDE_ROOT');
    if (!fs.existsSync(filePath)) throw new Error(`AUTHOR_STYLE_FILE_MISSING: ${relativePath}`);
    return { relativePath: slash(relativePath), filePath };
  });

  const pageFiles = (config.pages || []).map((page) => {
    if (!page || !page.id || !page.file) {
      throw new Error('AUTHOR_PAGE_ENTRY_INVALID: each page entry must define id and file');
    }
    const filePath = resolveInside(rootDir, page.file, 'AUTHOR_PAGE_FILE_OUTSIDE_ROOT');
    if (!fs.existsSync(filePath)) throw new Error(`AUTHOR_PAGE_FILE_MISSING: ${page.file}`);
    return { id: page.id, relativePath: slash(page.file), filePath };
  });

  if (pageFiles.length === 0) {
    throw new Error('AUTHOR_PAGE_LIST_EMPTY: deck.config.json must define at least one page');
  }

  return {
    rootDir,
    configPath: resolvedConfigPath,
    config,
    entryPath: resolveInside(rootDir, config.entry, 'AUTHOR_ENTRY_OUTSIDE_ROOT'),
    styleFiles,
    pageFiles,
  };
}

function assembleAuthorPackage(configPath) {
  const sourcePackage = readAuthorPackage(configPath);
  const styles = sourcePackage.styleFiles
    .map((file) => {
      const css = fs.readFileSync(file.filePath, 'utf8');
      return `<style data-source-file="${attr(file.relativePath)}">\n${css.trimEnd()}\n</style>`;
    })
    .join('\n');

  const pages = sourcePackage.pageFiles
    .map((file) => addSourceFileAttribute(fs.readFileSync(file.filePath, 'utf8'), file.relativePath))
    .join('\n\n');

  const title = sourcePackage.config.title || sourcePackage.config.id;
  const packageAttrs = [
    `data-id-document="${attr(sourcePackage.config.id)}"`,
    sourcePackage.config.profile ? `data-id-profile="${attr(sourcePackage.config.profile)}"` : null,
    `data-id-source-package-config="${attr(path.relative(sourcePackage.rootDir, sourcePackage.configPath).replace(/\\/g, '/'))}"`,
    `data-id-source-package-schema="${attr(sourcePackage.config.schemaVersion)}"`,
  ].filter(Boolean).join(' ');
  const html = [
    '<!doctype html>',
    '<html lang="zh-CN">',
    '<head>',
    '  <meta charset="utf-8">',
    `  <title>${escapeText(title)}</title>`,
    `  ${GENERATED_COMMENT}`,
    styles,
    '</head>',
    '<body>',
    `  <main class="deck" ${packageAttrs}>`,
    indent(pages, 4),
    '  </main>',
    '</body>',
    '</html>',
    '',
  ].join('\n');

  return { html, sourcePackage };
}

function writeAuthorPackageEntry(configPath) {
  const { html, sourcePackage } = assembleAuthorPackage(configPath);
  fs.writeFileSync(sourcePackage.entryPath, html, 'utf8');
  return { entryPath: sourcePackage.entryPath };
}

function checkAuthorPackageEntry(configPath) {
  const { html, sourcePackage } = assembleAuthorPackage(configPath);
  if (!fs.existsSync(sourcePackage.entryPath)) {
    return {
      ok: false,
      entryPath: sourcePackage.entryPath,
      message: 'generated deck.html is missing',
    };
  }
  const current = fs.readFileSync(sourcePackage.entryPath, 'utf8');
  if (current !== html) {
    return {
      ok: false,
      entryPath: sourcePackage.entryPath,
      message: 'generated deck.html is out of date',
    };
  }
  return { ok: true, entryPath: sourcePackage.entryPath };
}

function addSourceFileAttribute(fragment, sourceFile) {
  return fragment.replace(/<section\b([^>]*)>/i, (match, rest) => {
    if (/data-id-source-file\s*=/.test(rest)) return match;
    return `<section${rest} data-id-source-file="${attr(sourceFile)}">`;
  }).trimEnd();
}

function resolveInside(rootDir, relativePath, errorCode) {
  const target = path.resolve(rootDir, relativePath);
  const root = path.resolve(rootDir);
  const rootWithSeparator = root.endsWith(path.sep) ? root : `${root}${path.sep}`;
  if (target !== root && !target.startsWith(rootWithSeparator)) {
    throw new Error(`${errorCode}: ${relativePath}`);
  }
  return target;
}

function indent(value, spaces) {
  const prefix = ' '.repeat(spaces);
  return String(value).split(/\r?\n/).map((line) => (line ? `${prefix}${line}` : line)).join('\n');
}

function slash(value) {
  return String(value).replace(/\\/g, '/');
}

function attr(value) {
  return String(value).replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;');
}

function escapeText(value) {
  return String(value).replace(/&/g, '&amp;').replace(/</g, '&lt;');
}

module.exports = {
  GENERATED_COMMENT,
  assembleAuthorPackage,
  checkAuthorPackageEntry,
  readAuthorPackage,
  writeAuthorPackageEntry,
};
