const { HTML_DATA_ID_ATTRIBUTES } = require('../protocol');
const fs = require('fs');
const path = require('path');
const cheerio = require('cheerio');

const GENERATED_COMMENT = '<!-- Generated by html-indesign. Edit pages/*.html and styles/*.css, not this file. -->';
const RECOMMENDED_STYLE_FILES = [
  'styles/tokens.css',
  'styles/layout.css',
  'styles/components.css',
  'styles/pages.css',
];

function readAuthorPackage(configPath) {
  if (!configPath) throw new Error('AUTHOR_PACKAGE_CONFIG_MISSING: config path is required');
  const resolvedConfigPath = path.resolve(configPath);
  if (!fs.existsSync(resolvedConfigPath)) {
    throw new Error(`AUTHOR_PACKAGE_CONFIG_MISSING: ${resolvedConfigPath}`);
  }

  const rootDir = path.dirname(resolvedConfigPath);
  const config = JSON.parse(fs.readFileSync(resolvedConfigPath, 'utf8'));
  if (config.schemaVersion !== 1) {
    throw new Error(`AUTHOR_PACKAGE_SCHEMA_UNSUPPORTED: ${config.schemaVersion}`);
  }
  if (!config.id || typeof config.id !== 'string') {
    throw new Error('AUTHOR_PACKAGE_ID_MISSING: deck.config.json must define id');
  }
  if (!config.entry || typeof config.entry !== 'string') {
    throw new Error('AUTHOR_PACKAGE_ENTRY_MISSING: deck.config.json must define entry');
  }

  const styleFiles = (config.styles || []).map((relativePath) => {
    const filePath = resolveInside(rootDir, relativePath, 'AUTHOR_STYLE_FILE_OUTSIDE_ROOT');
    if (!fs.existsSync(filePath)) throw new Error(`AUTHOR_STYLE_FILE_MISSING: ${relativePath}`);
    return { relativePath: slash(relativePath), filePath };
  });

  const pageFiles = (config.pages || []).map((page) => {
    if (!page || !page.id || !page.file) {
      throw new Error('AUTHOR_PAGE_ENTRY_INVALID: each page entry must define id and file');
    }
    const filePath = resolveInside(rootDir, page.file, 'AUTHOR_PAGE_FILE_OUTSIDE_ROOT');
    if (!fs.existsSync(filePath)) throw new Error(`AUTHOR_PAGE_FILE_MISSING: ${page.file}`);
    return { id: page.id, relativePath: slash(page.file), filePath };
  });

  if (pageFiles.length === 0) {
    throw new Error('AUTHOR_PAGE_LIST_EMPTY: deck.config.json must define at least one page');
  }

  const semanticPreset = config.semanticPreset
    ? resolveSemanticPresetMetadata(rootDir, config.semanticPreset)
    : null;

  return {
    rootDir,
    configPath: resolvedConfigPath,
    config,
    entryPath: resolveInside(rootDir, config.entry, 'AUTHOR_ENTRY_OUTSIDE_ROOT'),
    styleFiles,
    pageFiles,
    semanticPreset,
  };
}

function loadAuthorPackageConfig(configPath) {
  if (!configPath) throw new Error('AUTHOR_PACKAGE_CONFIG_MISSING: config path is required');
  const resolvedConfigPath = path.resolve(configPath);
  if (!fs.existsSync(resolvedConfigPath)) {
    throw new Error(`AUTHOR_PACKAGE_CONFIG_MISSING: ${resolvedConfigPath}`);
  }
  const rootDir = path.dirname(resolvedConfigPath);
  const config = JSON.parse(fs.readFileSync(resolvedConfigPath, 'utf8'));
  if (config.schemaVersion !== 1) {
    throw new Error(`AUTHOR_PACKAGE_SCHEMA_UNSUPPORTED: ${config.schemaVersion}`);
  }
  if (!config.id || typeof config.id !== 'string') {
    throw new Error('AUTHOR_PACKAGE_ID_MISSING: deck.config.json must define id');
  }
  if (!config.entry || typeof config.entry !== 'string') {
    throw new Error('AUTHOR_PACKAGE_ENTRY_MISSING: deck.config.json must define entry');
  }
  return {
    rootDir,
    configPath: resolvedConfigPath,
    config,
  };
}

function assembleAuthorPackage(configPath) {
  const sourcePackage = readAuthorPackage(configPath);
  const styles = sourcePackage.styleFiles
    .map((file) => {
      const css = fs.readFileSync(file.filePath, 'utf8');
      return `<style data-source-file="${attr(file.relativePath)}">\n${css.trimEnd()}\n</style>`;
    })
    .join('\n');

  const pages = sourcePackage.pageFiles
    .map((file) => addSourceFileAttribute(fs.readFileSync(file.filePath, 'utf8'), file.relativePath))
    .join('\n\n');

  const title = sourcePackage.config.title || sourcePackage.config.id;
  const parentPagesMetadata = sourcePackage.config.parentPages && sourcePackage.config.parentPages.length
    ? `  <script type="application/json" ${HTML_DATA_ID_ATTRIBUTES.SOURCE_PACKAGE_PARENT_PAGES}>${jsonScript(sourcePackage.config.parentPages)}</script>`
    : null;
  const layersMetadata = sourcePackage.config.layers && sourcePackage.config.layers.length
    ? `  <script type="application/json" ${HTML_DATA_ID_ATTRIBUTES.SOURCE_PACKAGE_LAYERS}>${jsonScript(sourcePackage.config.layers)}</script>`
    : null;
  const compositeFontsMetadata = sourcePackage.config.compositeFonts && sourcePackage.config.compositeFonts.length
    ? `  <script type="application/json" ${HTML_DATA_ID_ATTRIBUTES.SOURCE_PACKAGE_COMPOSITE_FONTS}>${jsonScript(sourcePackage.config.compositeFonts)}</script>`
    : null;
  const packageAttrs = [
    `${HTML_DATA_ID_ATTRIBUTES.DOCUMENT}="${attr(sourcePackage.config.id)}"`,
    sourcePackage.config.profile ? `${HTML_DATA_ID_ATTRIBUTES.PROFILE}="${attr(sourcePackage.config.profile)}"` : null,
    `${HTML_DATA_ID_ATTRIBUTES.SOURCE_PACKAGE_CONFIG}="${attr(path.relative(sourcePackage.rootDir, sourcePackage.configPath).replace(/\\/g, '/'))}"`,
    `${HTML_DATA_ID_ATTRIBUTES.SOURCE_PACKAGE_SCHEMA}="${attr(sourcePackage.config.schemaVersion)}"`,
    sourcePackage.semanticPreset ? `${HTML_DATA_ID_ATTRIBUTES.SEMANTIC_PRESET}="${attr(sourcePackage.semanticPreset.relativePath)}"` : null,
  ].filter(Boolean).join(' ');
  const html = [
    '<!doctype html>',
    '<html lang="zh-CN">',
    '<head>',
    '  <meta charset="utf-8">',
    `  <title>${escapeText(title)}</title>`,
    `  ${GENERATED_COMMENT}`,
    styles,
    '</head>',
    '<body>',
    ...(parentPagesMetadata ? [parentPagesMetadata] : []),
    ...(layersMetadata ? [layersMetadata] : []),
    ...(compositeFontsMetadata ? [compositeFontsMetadata] : []),
    `  <main class="deck" ${packageAttrs}>`,
    indent(pages, 4),
    '  </main>',
    '</body>',
    '</html>',
    '',
  ].join('\n');

  return { html, sourcePackage };
}

function writeAuthorPackageEntry(configPath) {
  const { html, sourcePackage } = assembleAuthorPackage(configPath);
  fs.writeFileSync(sourcePackage.entryPath, html, 'utf8');
  return { entryPath: sourcePackage.entryPath };
}

function writeAuthorPackageConfig(configPath, config) {
  fs.writeFileSync(path.resolve(configPath), `${JSON.stringify(config, null, 2)}\n`, 'utf8');
}

function checkAuthorPackageEntry(configPath) {
  const { html, sourcePackage } = assembleAuthorPackage(configPath);
  if (!fs.existsSync(sourcePackage.entryPath)) {
    return {
      ok: false,
      entryPath: sourcePackage.entryPath,
      message: 'generated deck.html is missing',
    };
  }
  const current = fs.readFileSync(sourcePackage.entryPath, 'utf8');
  if (current !== html) {
    return {
      ok: false,
      entryPath: sourcePackage.entryPath,
      message: 'generated deck.html is out of date',
    };
  }
  return { ok: true, entryPath: sourcePackage.entryPath };
}

function auditAuthorPackageSourceFormat(configPath, options = {}) {
  let sourcePackage;
  try {
    sourcePackage = readAuthorPackage(configPath);
  } catch (error) {
    const issue = sourceIssue('error', 'AUTHOR_PACKAGE_INVALID', error.message || String(error), null);
    return formatAuditResult([issue], [], options);
  }

  const errors = [];
  const warnings = [];
  const styleSet = new Set(sourcePackage.styleFiles.map((file) => file.relativePath));
  for (const file of RECOMMENDED_STYLE_FILES) {
    if (!styleSet.has(file)) {
      warnings.push(sourceIssue('warning', 'AUTHOR_STYLE_BUCKET_MISSING', `Recommended authoring style file is missing: ${file}`, file));
    }
  }

  for (const page of sourcePackage.pageFiles) {
    const html = fs.readFileSync(page.filePath, 'utf8');
    auditPageFragment(page, html, errors, warnings);
  }

  return formatAuditResult(errors, warnings, options);
}

function auditPageFragment(page, html, errors, warnings) {
  if (/<\s*!doctype\b|<\s*html\b|<\s*head\b|<\s*body\b/i.test(html)) {
    errors.push(sourceIssue(
      'error',
      'AUTHOR_PAGE_FRAGMENT_FULL_DOCUMENT',
      'Page source files must be section fragments, not complete HTML documents.',
      page.relativePath
    ));
  }

  const $ = cheerio.load(html, {
    decodeEntities: false,
    xmlMode: false,
  });
  const pageSections = $('section.page, section[data-page]');
  if (pageSections.length !== 1) {
    errors.push(sourceIssue(
      'error',
      'AUTHOR_PAGE_SECTION_INVALID',
      'Each page source file must contain exactly one page section.',
      page.relativePath
    ));
    return;
  }

  const section = pageSections.first();
  for (const attrName of ['data-page', HTML_DATA_ID_ATTRIBUTES.LAYOUT, HTML_DATA_ID_ATTRIBUTES.MARGIN, HTML_DATA_ID_ATTRIBUTES.GRID]) {
    if (!hasNonEmptyAttribute(section, attrName)) {
      warnings.push(sourceIssue(
        'warning',
        'AUTHOR_PAGE_CONTRACT_MISSING',
        `Page section should declare ${attrName}.`,
        page.relativePath,
        { attribute: attrName }
      ));
    }
  }

  section.find('.grid-item').each((index, element) => {
    const node = $(element);
    const style = String(node.attr('style') || '');
    const missing = ['--grid-col', '--grid-span', '--grid-row', '--grid-row-span']
      .filter((name) => !new RegExp(`${escapeRegExp(name)}\\s*:`).test(style));
    if (missing.length) {
      errors.push(sourceIssue(
        'error',
        'AUTHOR_GRID_ITEM_COORDS_MISSING',
        'Grid items must declare --grid-col, --grid-span, --grid-row and --grid-row-span.',
        page.relativePath,
        {
          item: node.attr('id') || node.attr('class') || `${element.name || 'element'}:${index + 1}`,
          missing,
        }
      ));
    }
  });
}

function addSourceFileAttribute(fragment, sourceFile) {
  return fragment.replace(/<section\b([^>]*)>/i, (match, rest) => {
    if (new RegExp(`${escapeRegExp(HTML_DATA_ID_ATTRIBUTES.SOURCE_FILE)}\\s*=`).test(rest)) return match;
    return `<section${rest} ${HTML_DATA_ID_ATTRIBUTES.SOURCE_FILE}="${attr(sourceFile)}">`;
  }).trimEnd();
}

function formatAuditResult(errors, warnings, options = {}) {
  const strict = !!options.strict;
  const promoted = strict ? warnings.map((entry) => ({ ...entry, level: 'error' })) : [];
  const resultErrors = errors.concat(promoted);
  const resultWarnings = strict ? [] : warnings;
  return {
    valid: resultErrors.length === 0,
    errors: resultErrors,
    warnings: resultWarnings,
    messages: resultErrors.concat(resultWarnings),
  };
}

function sourceIssue(level, code, message, file, extra = {}) {
  return {
    level,
    code,
    message,
    ...(file ? { file } : {}),
    ...extra,
  };
}

function hasNonEmptyAttribute(node, name) {
  const value = node.attr(name);
  return value != null && String(value).trim() !== '';
}

function resolveInside(rootDir, relativePath, errorCode) {
  const target = path.resolve(rootDir, relativePath);
  const root = path.resolve(rootDir);
  const rootWithSeparator = root.endsWith(path.sep) ? root : `${root}${path.sep}`;
  if (target !== root && !target.startsWith(rootWithSeparator)) {
    throw new Error(`${errorCode}: ${relativePath}`);
  }
  return target;
}

function resolveSemanticPresetMetadata(rootDir, relativePath) {
  if (typeof relativePath !== 'string' || !relativePath.trim()) {
    throw new Error('AUTHOR_SEMANTIC_PRESET_INVALID: semanticPreset must be a non-empty relative path');
  }
  const filePath = resolveInside(rootDir, relativePath, 'AUTHOR_SEMANTIC_PRESET_OUTSIDE_ROOT');
  if (!fs.existsSync(filePath)) throw new Error(`AUTHOR_SEMANTIC_PRESET_MISSING: ${relativePath}`);
  return {
    relativePath: slash(relativePath),
    filePath,
  };
}

function indent(value, spaces) {
  const prefix = ' '.repeat(spaces);
  return String(value).split(/\r?\n/).map((line) => (line ? `${prefix}${line}` : line)).join('\n');
}

function slash(value) {
  return String(value).replace(/\\/g, '/');
}

function attr(value) {
  return String(value).replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;');
}

function escapeText(value) {
  return String(value).replace(/&/g, '&amp;').replace(/</g, '&lt;');
}

function jsonScript(value) {
  return JSON.stringify(value).replace(/</g, '\\u003c').replace(/\u2028/g, '\\u2028').replace(/\u2029/g, '\\u2029');
}

function escapeRegExp(value) {
  return String(value).replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

module.exports = {
  GENERATED_COMMENT,
  auditAuthorPackageSourceFormat,
  assembleAuthorPackage,
  checkAuthorPackageEntry,
  loadAuthorPackageConfig,
  readAuthorPackage,
  writeAuthorPackageConfig,
  writeAuthorPackageEntry,
};
