/**
 * HTML Validator for InDesign Blueprint Protocol
 * 
 * Implements the 'validation-engine' capability defined in Open Spec.
 */

const cheerio = require('cheerio');
// In a real build, we would import the constants, but for this simple JS implementation 
// we will define them or import if we set up TS compilation. 
// To keep it simple and runnable immediately with 'node', I'll use raw strings 
// matching the spec, or require if I converted them to JS. 
// For now, I'll hardcode the string constants to match the spec exactly.

const ERRORS = {
  MASTER_NOT_FOUND: 'MASTER_NOT_FOUND',
  SLOT_NOT_FOUND: 'SLOT_NOT_FOUND',
  TYPE_MISMATCH: 'TYPE_MISMATCH',
  MISSING_ATTRIBUTE: 'MISSING_ATTRIBUTE',
  STYLE_NOT_FOUND: 'STYLE_NOT_FOUND'
};

/**
 * Validates HTML content against a Blueprint JSON.
 * @param {string} html - The raw HTML string generated by AI.
 * @param {object} blueprint - The parsed blueprint.json object.
 * @returns {object} { valid: boolean, errors: Array }
 */
function validate(html, blueprint) {
  const $ = cheerio.load(html);
  const errors = [];
  
  // 1. Find all Master Sections
  const $sections = $('section[data-master], section[data-template]');
  
  // CHECK 0: Ensure at least one data-master section exists
  if ($sections.length === 0) {
    // Check if there's any section without data-master
    const $allSections = $('section');
    if ($allSections.length > 0) {
      errors.push({
        code: ERRORS.MISSING_ATTRIBUTE,
        location: 'Document root',
        message: 'Found section elements without data-master attribute.',
        suggestion: 'Add data-master="MasterPageName" to each section element.'
      });
    } else {
      errors.push({
        code: ERRORS.MISSING_ATTRIBUTE,
        location: 'Document root', 
        message: 'No page sections found in HTML.',
        suggestion: 'Wrap page content in <section data-master="MasterPageName">...</section>'
      });
    }
  }

  $sections.each((i, section) => {
    const $sec = $(section);
    const masterName = $sec.attr('data-master');
    const template = $sec.attr('data-template');
    const location = `Section ${i+1} (Master: "${masterName}")`;

    // CHECK 1: Master Page Existence (including free template master)
    const masterDef = masterName ? blueprint.masters[masterName] : undefined;
    if (masterName && !masterDef) {
      errors.push({
        code: ERRORS.MASTER_NOT_FOUND,
        location: location,
        message: `Master page '${masterName}' not found in blueprint.`,
        suggestion: `Available masters: ${Object.keys(blueprint.masters).join(', ')}`
      });
      return; // Cannot validate slots if master doesn't exist
    }

    // 2. Validate Slots within this Master
    if (!template || template.toLowerCase() !== 'free') {
      // BUG-008 fix: three-level slot lookup helper (same as builder.js)
      const normalize = (s) => (s || '').replace(/\s+/g, '').toLowerCase();
      const parseSlotName = (label) => {
        if (!label) return label;
        const segments = label.split(/[;；\n]/);
        for (const segRaw of segments) {
          const seg = segRaw.trim();
          if (!seg) continue;
          const parts = seg.split(/[:=：]/);
          if (parts.length < 2) continue;
          const key = parts.shift().trim();
          const val = parts.join('=').trim();
          if (!val) continue;
          if (['名称', '名字', '槽位', 'slot', 'name'].includes(key)) {
            return val;
          }
        }
        return label;
      };
      const lookupSlot = (slotName, slots) => {
        // 1. 精确匹配
        if (slots[slotName]) return slots[slotName];
        // 2. 标准化匹配
        const normName = normalize(slotName);
        let hit = Object.keys(slots).find(k => normalize(k) === normName);
        if (hit) return slots[hit];
        // 3. 解析简短名称后匹配
        hit = Object.keys(slots).find(k => {
          const parsedName = parseSlotName(k);
          return normalize(parsedName) === normName;
        });
        return hit ? slots[hit] : undefined;
      };

      const $slots = $sec.find('[data-slot]');
      $slots.each((j, slot) => {
        const $slot = $(slot);
        const slotName = $slot.attr('data-slot');
        const slotLocation = `${location} -> Slot "${slotName}"`;

        // CHECK 2: Slot Consistency (BUG-008 fix: use three-level lookup)
        const slotDef = lookupSlot(slotName, masterDef.slots || {});
        if (!slotDef) {
          const available = Object.keys(masterDef.slots || {});
          errors.push({
            code: ERRORS.SLOT_NOT_FOUND,
            location: slotLocation,
            message: `Slot '${slotName}' does not exist on master '${masterName}'.`,
            suggestion: `Available slots: ${available.join(', ')}`
          });
          return;
        }

        // CHECK 3: Content Type Validation
        if (slotDef.type === 'IMAGE') {
          // Expecting <img> tag
          const hasImg = $slot.is('img') || $slot.find('img').length > 0;
          const textContent = $slot.text().trim();

          if (!hasImg && textContent.length > 0) {
             errors.push({
               code: ERRORS.TYPE_MISMATCH,
               location: slotLocation,
               message: `Slot '${slotName}' is an IMAGE slot but contains text content.`,
               suggestion: `Use an <img src="..."> tag.`
             });
          }
        } else if (slotDef.type === 'TEXT') {
          // No strict checks for TEXT
        }
      });
    } else {
      // Free template: validate declared styles exist in blueprint
      const paraStyles = blueprint.paragraphStyles || {};
      const charStyles = blueprint.characterStyles || {};
      const objStyles = blueprint.objectStyles || {};
      const $items = $sec.find('[data-type]');
      $items.each((j, item) => {
        const $item = $(item);
        const itemLoc = `${location} -> Free item ${j + 1}`;

        // BUG-008 fix: validate bounds for free page items
        const bounds = $item.attr('data-bounds');
        const style = $item.attr('style') || '';
        const hasPositionStyle = style.includes('left:') && style.includes('top:') &&
                                  style.includes('width:') && style.includes('height:');

        if (!bounds && !hasPositionStyle) {
          errors.push({
            code: 'MISSING_BOUNDS',
            location: itemLoc,
            message: 'Free page item missing data-bounds or position styles.',
            suggestion: 'Add data-bounds="x,y,width,height" or style="left:x;top:y;width:w;height:h"'
          });
        }

        if (bounds) {
          const parts = bounds.split(',');
          if (parts.length !== 4) {
            errors.push({
              code: 'INVALID_BOUNDS',
              location: itemLoc,
              message: `Invalid bounds format: "${bounds}". Expected "x,y,width,height".`,
              suggestion: 'Use format: data-bounds="10mm,20mm,100mm,50mm" (4 comma-separated values)'
            });
          }
        }

        const ps = $item.attr('data-paragraph-style');
        if (ps && !paraStyles[ps]) {
          errors.push({
            code: ERRORS.STYLE_NOT_FOUND,
            location: itemLoc,
            message: `Paragraph style '${ps}' not found in blueprint.`,
            suggestion: `Available: ${Object.keys(paraStyles).join(', ')}`
          });
        }
        const cs = $item.attr('data-character-style');
        if (cs && !charStyles[cs]) {
          errors.push({
            code: ERRORS.STYLE_NOT_FOUND,
            location: itemLoc,
            message: `Character style '${cs}' not found in blueprint.`,
            suggestion: `Available: ${Object.keys(charStyles).join(', ')}`
          });
        }
        const os = $item.attr('data-object-style');
        if (os && !objStyles[os]) {
          errors.push({
            code: ERRORS.STYLE_NOT_FOUND,
            location: itemLoc,
            message: `Object style '${os}' not found in blueprint.`,
            suggestion: `Available: ${Object.keys(objStyles).join(', ')}`
          });
        }
      });
    }
  });

  return {
    valid: errors.length === 0,
    errors: errors
  };
}

module.exports = { validate, ERRORS };
